{{- if $.Values.robot.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datasets
  labels:
    app: datasets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datasets
  template:
    metadata:
      labels:
        app: datasets
    spec:
      serviceAccountName: jump-sa
      containers:
        - name: datasets
          image: "{{ .Values.global.repository }}{{ .Values.robot.datasets.image.repository }}:{{ .Values.robot.datasets.image.tag }}"
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          command: [ "docker-entrypoint.sh" ]
          args: [ "node", "server.js"]
          env:
            - name: NEXT_PUBLIC_USE_HUGGINGFACE
              value: "false"
            - name: NEXT_PUBLIC_S3_DATASET_PREFIX
              value: "s3://xlab-eks/datasets/"
            - name: AWS_REGION
              value: "us-west-2"
          workingDir: /app
          resources:
          {{- toYaml .Values.robot.datasets.resources | nindent 12 }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: datasets
spec:
  selector:
    app: datasets
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: datasets
spec:
  parentRefs:
    - name: eg
  hostnames:
    - datasets.{{ .Values.global.wildcardHost }}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: datasets
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
---
{{- end }}