apiVersion: v2
name: charts
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: gateway-helm
    version: "1.5.4"
    repository: "oci://docker.io/envoyproxy"