name: Deploy Helm to EKS

on:
  push:
    branches:
      - main
    tags:
      - v*
env:
  AWS_ACCOUNT_ID: 867344450900
  AWS_REGION: us-west-2
  EKS_CLUSTER: orbit

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionsRole
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy helm Amazon EKS
      uses: bitovi/github-actions-deploy-eks-helm@v1.2.12
      with:
        aws-region: ${{ env.AWS_REGION }}
        cluster-name: ${{ env.EKS_CLUSTER }}
        chart-path: charts/
        namespace: aws300
        name: app
        config-files: charts/values/values.beta.yaml
