name: Build dockers and push it to Amazon ECR

on:
  push:
    tags:
      - docker*

env:
  AWS_REGION: us-west-2
  ECR_REPOSITORY_NAMESPACE: aws300

permissions:
  contents: read

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Dockers
        id: build_dockers
        run: |
          export REGISTRY=${{ steps.login-ecr.outputs.registry }}
          export REPOSITORY_NAMESPACE=$ECR_REPOSITORY_NAMESPACE
          echo "Use image: $IMAGE_PREFIX"
          cd docker && chmod +x build.sh && ./build.sh
